--QUES1:
alter table EMPLOYEES
modify (LAST_NAME VARCHAR(40));

--QUES2:
CREATE TABLE EMPLOYEES2 AS
SELECT EMPLOYEE_ID AS ID, FIRST_NAME AS FIRST_NAME,
LAST_NAME AS LAST_NAME, SALARY AS SALARY, DEPARTMENT_ID AS DEPT_ID
FROM EMPLOYEES;

--QUES3
DROP TABLE EMPLOYEES2;

--QUES4
RENAME EMPLOYEES2 TO EMP_TAB;

--QUES5
COMMENT ON TABLE EMP_TAB
IS 'Employees Information';

--QUES6
ALTER TABLE EMP_TAB
DROP COLUMN FIRST_NAME;
DESC EMP_TAB;

--QUES7
ALTER TABLE EMP_TAB
SET UNUSED (DEPT_ID);
DESC EMP_TAB;

--QUES8
ALTER TABLE EMP_TAB
DROP UNUSED COLUMNS;

